apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: noodles-prod
  source:
    chart: redis
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: "21.2.13"  # Use latest stable version
    helm:
      releaseName: noodles-redis
      # values: |
  
  destination:
    server: https://kubernetes.default.svc
    namespace: noodles-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true