apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  type: ClusterIP
  ports:
    - port: 5672   # AMQP
      name: amqp
    - port: 15672  # Management UI
      name: management
  selector:
    app: rabbitmq
