apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noodles-postgres
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: postgres
  source:
    chart: postgresql
    repoURL: oci://registry-1.docker.io/bitnamicharts/postgresql
    targetRevision: "16.7.21"  # Use latest stable version
    helm:
      releaseName: noodles-postgres
      # values: |
  
  destination:
    server: https://kubernetes.default.svc
    namespace: noodles-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true