apiVersion: v1
kind: Secret
metadata:
  name: argocd-enable-bitnami-oci-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: argocd-enable-bitnami-oci-helm-repo
  url: oci://registry-1.docker.io/bitnamicharts
  enableOCI: "true"
  type: helm