apiVersion: v1
kind: Secret
metadata:
  name: noodles-github-argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/minswap/noodles-deploy.git
  password: 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
  username: nkciam
type: Opaque
# For GitOps, use environment variable substitution or SealedSecrets to avoid committing real secrets.
