---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana-stack
  namespace: argocd
spec:
  project: noodles
  source:
    repoURL: 'https://github.com/minswap/noodles-deploy.git'
    targetRevision: HEAD
    path: infrastructure/monitoring/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
