---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noodles-fe-apps
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      noodles-fe=minswap/noodles-fe:latest
    argocd-image-updater.argoproj.io/noodles-fe.allow-tags: >
      ^main-[0-9]{8}-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/noodles-fe.update-strategy: latest
    argocd-image-updater.argoproj.io/noodles-fe.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: auto-image-update
    argocd-image-updater.argoproj.io/pr-create: "true"
spec:
  generators:
    - list:
        elements:
          - cluster: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-noodles-fe'
    spec:
      project: noodles-prod
      source:
        repoURL: 'https://github.com/minswap/noodles-deploy.git'
        targetRevision: main
        path: 'apps/noodles-fe/overlays/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: noodles-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
