---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noodles-fe
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: >
      noodles-fe=minswap/noodles-fe:latest
    argocd-image-updater.argoproj.io/noodles-fe.allow-tags: >
      ^main-[0-9]{8}-[a-f0-9]{7}$
    argocd-image-updater.argoproj.io/noodles-fe.update-strategy: latest
    argocd-image-updater.argoproj.io/noodles-fe.force-update: "true"
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: auto-image-update
    argocd-image-updater.argoproj.io/pr-create: "true"
spec:
  project: noodles
  source:
    repoURL: 'https://github.com/minswap/noodles-deploy.git'
    targetRevision: main
    path: apps/noodles-fe/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: noodles-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
