---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: noodles-be-apps
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: prod
            url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-noodles-be'
    spec:
      project: noodles
      source:
        repoURL: 'https://github.com/minswap/noodles-deploy.git'
        targetRevision: main
        path: 'apps/noodles-be/overlays/{{cluster}}'
      destination:
        server: '{{url}}'
        namespace: noodles-prod
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
