---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noodles-redis
  namespace: argocd
spec:
  project: noodles-prod
  source:
    repoURL: 'https://github.com/minswap/noodles-deploy.git'
    targetRevision: HEAD
    path: infrastructure/redis/overlays/prod
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: noodles-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
